version: '3.9'

services:
  db:
    build:
      dockerfile: docker/postgres/Dockerfile
    restart: always
    networks:
      - fullstack
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - dartsly-match-service-volume:/var/lib/postgresql/data

volumes:
  dartsly-match-service-volume:
    external: true


networks:
  fullstack:
    driver: bridge