name: Build Lint and Test Lambda

on: 
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build_lint:
        runs-on: ubuntu-latest
        name: Checks
        steps:
          - name: Checkout Project
            uses: actions/checkout@v3
            with:
              ref: ${{ github.ref }}
          - name: Setup Go
            uses: actions/setup-go@v4
            with:
              go-version: '>=1.20.0'
          - run: go version
          - name: Go Vet
            run: go vet ./...
          - name: lint
            uses: golangci/golangci-lint-action@v3
            with:
              version: v1.54
          - name: Go Mod Init
            run: go mod download
          - name: Go Test
            run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v3
            env:
              CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            with:
              files: coverage.out